# Generated by Django 5.2.9 on 2025-12-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_uploadeddocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadeddocument',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
